spring.application.name=campuscarry

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/campuscarry
spring.datasource.username=postgres
spring.datasource.password=Lancersfx
spring.datasource.driver-class-name=org.postgresql.Driver

# Server
server.port=8080
server.servlet.context-path=/api/v1

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


## JWT
jwt.secret=campuscarry_super_secret_key_2024_replace_in_prod
jwt.expiration=86400000
jwt.refresh-expiration=604800000

## Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=megh.chakravarty8046@gmail.com
spring.mail.password=njoomldemcqdcmdb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Rate limiting
app.rate-limit.auth-requests-per-minute=5
app.rate-limit.api-requests-per-minute=60
app.rate-limit.otp-cooldown-minutes=2

# Idempotency
app.idempotency.ttl-minutes=5

# Razorpay
razorpay.key.id=rzp_test_Sy5xKwz7fldO6o
razorpay.key.secret=YQ5LaVYjpW0Rtzp5pgootTcp
razorpay.currency=INR
razorpay.company.name=CampusCarry